In [49]:
import numpy as np

In [51]:
#for finding mode
from scipy import stats
#or
import statistics as st

In [53]:
data = np.array([30, 10, 70, 40, 80, 50, 100, 15, 10, 70])

In [55]:
print(data)

[ 30  10  70  40  80  50 100  15  10  70]


In [57]:
mean = np.mean(data)

In [59]:
print("Mean = ",mean)

Mean =  47.5


In [61]:
median = np.median(data)

In [63]:
print ("Median = ",median)

Median =  45.0


In [65]:
mode = stats.mode(data) 
#mode = st.mode(data)

In [67]:
print("Mode =",mode)

Mode = ModeResult(mode=10, count=2)


In [69]:
sd = np.std(data)

In [71]:
print("Standard Deviation =",sd)

Standard Deviation = 30.103986446980738


In [73]:
var = np.var(data)

In [75]:
print("Variance =", var)

Variance = 906.25


In [77]:
# ptp denotes peak to peak and it returns the range of values (maximum-minimum) along an axis.
rg = np.ptp(data)

In [79]:
#Range = Max – Min. 100 - 10
print("Range =",rg)

Range = 90


In [81]:
absDev = np.abs(data - mean)

In [83]:
print("Absolute Deviation =",absDev)

Absolute Deviation = [17.5 37.5 22.5  7.5 32.5  2.5 52.5 32.5 37.5 22.5]


In [85]:
absMeanDev = np.mean(absDev)

In [87]:
print("Absolute Mean Deviation =",absMeanDev)

Absolute Mean Deviation = 26.5


In [89]:
#Outliers are numbers in a data set that are vastly larger or smaller than the other values in the set, here 5555
data =np.insert(data, 3,5555)

In [124]:
print(data)

[  30   10   70 5555   40   80   50  100   15   10   70]


In [91]:
mean2 = np.mean(data)
median2 = np.median(data)
mode2 = stats.mode(data)
sd2 = np.std(data)

In [93]:
#due to outlier in mean and Standard Deviation is affected more but median and mode does not afefct much
print("MEAN =", mean2)
print("MEDIAN =",median2)
print("MODE =",mode2)
print("Standard Deviation =", sd2)

MEAN = 548.1818181818181
MEDIAN = 50.0
MODE = ModeResult(mode=10, count=2)
Standard Deviation = 1583.5550808907394


In [95]:
#Detecting outlier in the dataset using different methods such as the Z-score, Interquartile Range (IQR), and Tukey’s Fences
#these methods identify data points that significantly differ from others in the dataset, improving data analysis and accuracy

In [97]:
#Z-score method uses standard deviation to determine outliers
#Calculated z-score > threshold is considered an outlier
#Threshold generally lies between 2 to 3

In [107]:
outliers =[]
threshhold = 3;
for x in data:
    z_score = (x - mean)/sd       #put actual mean
    if abs(z_score) > threshhold:
        outliers.append(x)

In [ ]:
print("outliers is ", outliers)

Method 2: Interquartile Range (IQR)

In [112]:
#find IQR of data by subtracting q1 from q3 .If the value/data point is more than 1.5 times the iqr it will be considered an outlier.
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

In [116]:
print(q1)
print(q3)

22.5
75.0


In [118]:
iqr = q3 - q1
threshold = 1.5 * iqr
outliers = np.where((data < q1 - threshold) | (data > q3 + threshold))
#calculate percentile of 25th and 75th set threshold to 1.5 times iqr

In [128]:
print(threshold)

78.75


In [120]:
print(iqr)

52.5


In [122]:
print(outliers)

(array([3], dtype=int64),)


In [126]:
print("Outliers of array ",data,"is : \n", data[outliers])

Outliers of array  [  30   10   70 5555   40   80   50  100   15   10   70] is : 
 [5555]
