In [17]:
import numpy as np

In [26]:
arr1 = np.array([[1,2,3], [4,5, 6],[1,2,1]])

In [28]:
arr2 = np.array([[1,1,1], [0,1,0],[1,5,3]])

In [30]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [1 2 1]]


In [32]:
print(arr2)

[[1 1 1]
 [0 1 0]
 [1 5 3]]


In [50]:
arr3 = np.multiply(arr1, arr2)

In [44]:
print (arr3)

[[ 1  2  3]
 [ 0  5  0]
 [ 1 10  3]]


In [56]:
#calculating dot product
arr3 = np.dot(arr1, arr2)

In [58]:
print (arr3)

[[ 4 18 10]
 [10 39 22]
 [ 2  8  4]]


In [62]:
#calculating cross product
arr3 = arr1@arr2

In [64]:
print (arr3)

[[ 4 18 10]
 [10 39 22]
 [ 2  8  4]]


In [68]:
sum = np.add(arr1, arr2)

In [70]:
print (sum)

[[2 3 4]
 [4 6 6]
 [2 7 4]]


In [72]:
sub = np.subtract(arr1, arr2)

In [74]:
print (sub)

[[ 0  1  2]
 [ 4  4  6]
 [ 0 -3 -2]]


In [78]:
div = np.divide(arr2, arr1)

In [80]:
print (div)

[[1.         0.5        0.33333333]
 [0.         0.2        0.        ]
 [1.         2.5        3.        ]]
